version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      time: "13:35"
      # Use Poland Standard Time (UTC +01:00)
      timezone: "Europe/Warsaw"
