env:
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - prettier
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - unused-imports
  - prettier
rules:
  unused-imports/no-unused-imports-ts: error
  prettier/prettier: error
ignorePatterns: ['**/dist']
